version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
      types:
        patterns:
          - "@types/*"
